In [3]:
import numpy as np
a1 = np.random.randint(1,20,15)
print(a1)
a2=np.reshape(a1,(3,5))
print(a2)
print(a2.shape)
max_element = np.amax(a2, axis = 1)
max_element = max_element[: , None]
a3 = np.where(a2 == max_element, 0, a2)
print(a3)

[ 9  6 16 17 10 10 16  7 18  3  9  7 16  6  3]
[[ 9  6 16 17 10]
 [10 16  7 18  3]
 [ 9  7 16  6  3]]
(3, 5)
[[ 9  6 16  0 10]
 [10 16  7  0  3]
 [ 9  7  0  6  3]]


In [1]:
import numpy as np

# Create a 2-dimensional array of size 4x3 with 4-byte integer elements
array = np.zeros((4, 3), dtype=np.int32)

# Print the array
print("Array:")
print(array)

# Print the shape of the array
print("Shape of the array:", array.shape)

# Print the type of the array
print("Type of the array:", type(array))

# Print the data type of the array elements
print("Data type of the array elements:", array.dtype)


Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array elements: int32


In [4]:
import numpy as np

# Define the square matrix
matrix = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the results
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [5]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Find the minimum dimension to handle non-square matrices
min_dim = min(array.shape)

# Compute the sum of the diagonal elements
diagonal_sum = np.sum([array[i, i] for i in range(min_dim)])

# Print the result
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [6]:
import numpy as np

# Define the original array
original_array = np.array([[1, 2], [3, 4], [5, 6]])

# Print the original array and its shape
print("Original array:")
print(original_array)
print("Shape of original array:", original_array.shape)

# Reshape the array to a new shape (2, 3)
new_shape = (2, 3)
reshaped_array = original_array.reshape(new_shape)

# Print the reshaped array and its new shape
print("\nReshaped array:")
print(reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)


Original array:
[[1 2]
 [3 4]
 [5 6]]
Shape of original array: (3, 2)

Reshaped array:
[[1 2 3]
 [4 5 6]]
Shape of reshaped array: (2, 3)
